apiVersion: v1
kind: Service
metadata:
  name: auto-workflow
  namespace: workflow-ns
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: auto-workflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080